namespace: rare
name: freertr
version: 1.0.0
readme: README.md
authors:
- Justas Balcas <juztas@gmail.com>
description: Ansible Network Collections for RARE FreeRTR
license_file: LICENCE
tags: [RARE, freeRTR, networking, P4]
dependencies:
  ansible.netcommon: '>=1.0.0'
repository: https://github.com/sdn-sense/sense-freertr-collection
documentation: https://github.com/sdn-sense/sense-freertr-collection
homepage: https://github.com/sdn-sense/sense-freertr-collection
issues: https://github.com/sdn-sense/sense-freertr-collection
